# Generated by Django 5.2.5 on 2025-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_progressupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
